ProjectSSMP/Controllers/UserManagenentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectSSMP.Models;
using ProjectSSMP.Models.UserManagement;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProjectSSMP.Controllers
{
    public class UserManagementController : Controller
    {
        private readonly sspmContext _context;

        public UserManagementController(sspmContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(AddUserInputModel inputModel)
        {
            try
            {
                //var loggedInUser = HttpContext.User;
                //var loggedInUserName = loggedInUser.Identity.Name;

                var id = (from u in _context.RunningNumber where u.Type.Equals("UserID") select u).FirstOrDefault();

                int userid;
                if (id.Number == null)
                {
                    userid = 100001;

                }
                else
                {
                    userid = Convert.ToInt32(id.Number);
                    userid = userid + 1;
                }

                UserSspm ord = new UserSspm
                {
                    UserId = userid.ToString(),
                    Username = inputModel.Username,
                    Password = inputModel.Password,
                    Firstname = inputModel.Firstname,
                    Lastname = inputModel.Lastname,
                    JobResponsible = inputModel.JobResponsible,
                    UserCreateBy = "Test",
                    UserCreateDate = DateTime.Now,



                };

                UserAssignGroup ord2 = new UserAssignGroup
                {
                    UserId = userid.ToString(),
                    GroupId = inputModel.GroupID,

                };

                // Add the new object to the Orders collection.
                _context.UserSspm.Add(ord);
                await _context.SaveChangesAsync();
                _context.UserAssignGroup.Add(ord2);
                await _context.SaveChangesAsync();

                var query = from num in _context.RunningNumber
                                           where num.Type.Equals("UserID") 
                                                select num;

                foreach (RunningNumber RunUserID in query)
                {
                    RunUserID.Number = userid.ToString();

                }

                // Submit the changes to the database.
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    // Provide for exceptions.
                }

                return RedirectToAction("Index", "Home");



            }
            catch (Exception ex)
            {
                var message = ex.Message;
                return View();
            }
        }
    }
}

ProjectSSMP/Views/UserManagement/AddUser.cshtml
@{
    ViewData["Title"] = "Add User";
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}

<div class="container">
    <h1 class="well">Add User</h1>
    <div class="col-lg-12 well">
    <div class="row">
                <form asp-controller="UserManagement" asp-action="AddUser" method="post">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label>Username</label>
                                <input type="text" name="Username" id="Username" placeholder="Enter Username Here.." class="form-control">
                            </div>
                            <div class="col-sm-6 form-group">
                                <label>Password</label>
                                <input type="text" name="Password" id="Password" placeholder="Enter Password Here.." class="form-control">
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label>First Name</label>
                                <input type="text" name="Firstname" id="Firstname" placeholder="Enter First Name Here.." class="form-control">
                            </div>
                            <div class="col-sm-6 form-group">
                                <label>Last Name</label>
                                <input type="text" name="Lastname" id="Lastname" placeholder="Enter Last Name Here.." class="form-control">
                            </div>
                        </div>                  
                         
                        
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label>Job Title</label>
                                <input type="text" name="JobResponsible" id="JobResponsible" placeholder="Enter Designation Here.." class="form-control">
                            </div>      
                            <div class="col-sm-6 form-sgroup">
                                <label>Group</label>
                                <div class="form-group">
                                             <select class="form-control" name="GroupID" id="GroupID" >
                                             <option value="50">Project Manager</option>
                                             <option value="10">Team</option>
                                             </select>
                                        </div>
                            </div>  
                        </div>                      
                   
                    <button type="submit" class="btn btn-lg btn-info">Submit</button>                   
                    </div>
                </form> 
                </div>
    </div>
    </div>